alias gita='git add'
alias gitb='git branch'
alias gitc='git commit'
alias gitct='git commit -u'
alias gitco='git checkout'
alias gitm='git merge'
# Remove Files
alias gitrm='git remove -v'
# Discard Changes
alias gitdc='git checkout --'
alias gitrh='git reset add'
alias gitps='git push'
alias gitpl='git pull'
alias gitrem='git remote -v'
alias gitl='git log --color'
alias gitl1='git log --oneline --color'
alias gits='git status'
alias gitd='git diff --color'
alias gitdone='git diff --oneline --color'
